version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "<task-def-arn>"
        LoadBalancerInfo:
          ContainerName: "wildrydes-container"
          ContainerPort: 80
