version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "REPLACED_AT_DEPLOY_TIME"
        LoadBalancerInfo:
          ContainerName: "wildrydes-container"
          ContainerPort: 80
