version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 904233128713.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=904233128713.dkr.ecr.us-east-1.amazonaws.com/wild-rydes-app
      - IMAGE_TAG=latest  # You can change 'latest' to any tag you prefer
  build:
    commands:
      - echo "Build started on $(date)"
      - docker build -t 904233128713.dkr.ecr.us-east-1.amazonaws.com/wild-rydes-app:latest .
  post_build:
    commands:
      - echo "Build completed on $(date)"
      - docker push 904233128713.dkr.ecr.us-east-1.amazonaws.com/wild-rydes-app:latest
      - echo "Pushed to ECR successfully"
      - echo Writing image definitions...
      - printf '[{"name":"wildrydes-container","imageUri":"904233128713.dkr.ecr.us-east-1.amazonaws.com/wild-rydes-app:latest"}]' > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
