version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      # Install the AWS CLI
      - echo Installing AWS CLI
      - pip install --upgrade awscli
      # Authenticate Docker to Amazon ECR
      - echo Logging in to Amazon ECR
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t wildrydes-app .
      - echo Tagging the Docker image with the ECR URI
      - docker tag wildrydes-app:latest ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/wildrydes-repo:latest
  post_build:
    commands:
      - echo Pushing the Docker image to Amazon ECR
      - docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/wildrydes-repo:latest
      - echo Image URI: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/wildrydes-repo:latest

artifacts:
  files: '**/*'
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'
